# Generated by Django 5.2.17 on 2026-08-11 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('suspended', models.BooleanField(default=False)),
                ('licensed_states', models.JSONField(default=list)),
                ('service_area_zip_prefixes', models.JSONField(default=list)),
                ('minimum_price', models.PositiveIntegerField(default=0)),
                ('maximum_price', models.PositiveIntegerField(default=2000000)),
                ('capacity', models.PositiveIntegerField(default=5)),
                ('active_referral_count', models.PositiveIntegerField(default=0)),
                ('performance_score', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=64)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=10)),
                ('estimated_price', models.PositiveIntegerField()),
                ('intent_level', models.CharField(choices=[('browsing', 'Browsing'), ('warm', 'Warm'), ('hot', 'Hot')], default='warm', max_length=16)),
                ('status', models.CharField(choices=[('new', 'New'), ('offered', 'Offered'), ('assigned', 'Assigned'), ('closed', 'Closed')], default='new', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_referrals', to='referrals.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility_snapshot', models.JSONField(default=dict)),
                ('score', models.FloatField()),
                ('score_explanation', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='referrals.agent')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='referrals.referral')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='referrals.agent')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='referrals.referral')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('referral_received', 'Referral Received'), ('candidates_generated', 'Candidates Generated'), ('offer_sent', 'Offer Sent'), ('offer_viewed', 'Offer Viewed'), ('claim_attempted', 'Claim Attempted'), ('claim_succeeded', 'Claim Succeeded'), ('claim_conflicted', 'Claim Conflicted'), ('offer_declined', 'Offer Declined'), ('offer_expired', 'Offer Expired'), ('ops_override', 'Ops Override')], max_length=32)),
                ('actor', models.CharField(blank=True, default='', max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='referrals.referral')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
